### ISSUE TITLE
Shadowlands Shaman Changes

### ISSUE THREAD

**Issue by icbat** [VgerMods/HearKitty#2]
Heya! I'd like to take a stab at updating this for the new Shaman spec changes upcoming in Shadowlands. Just wanted to start a conversation about it and see where your head was at as far as accepting contributions.

**Comment by TravisSpomer** [comment]
Hi! Sorry for missing this; it turns out since this project is in the VgerMods "organization" instead of my personal account, I don't get notifications for comments and PRs by default. 😬 Would this be for enhancement? I play elemental and resto and those appear to be fine, but I did see that enhancement got some more significant changes.

I would be open to contributions as long as it's something small and targeted, like "copy and paste this block and add a spell ID for Fulmination." If the required changes end up being something bigger, I'd prefer to do those sorts of things myself. Or if your answer is "yeah I offered six weeks ago, too late, bucko" that's fine too!

**Comment by icbat** [comment]
Oh hey! No worries :) I had spell IDs handy 6 weeks ago, but it's been a while. It was a tad bit tricky as there are several buffs called Maelstrom Weapon, only one of which stacks correctly. 

I'm also a bit opinionated as to when I want the sounds, so I think I'll probably end up making a WeakAura or my own small addon to handle this. I'll leave these changes to you :) thanks for your response!
